### ISSUE TITLE
v2.1 installation instructions use a version of Ruby that is no longer maintained 

### ISSUE THREAD

**Issue by marks** [pophealth/popHealth#137] opened 2014-03-24 13:00 UTC
Following https://github.com/pophealth/popHealth/wiki/Installation-v2.1 and received the following (note "WARNING" toward the bottom) 

```
root@precise32:~# rvm install 1.9.3-p385
Searching for binary rubies, this might take some time.
No binary rubies available for: ubuntu/12.04/i386/ruby-1.9.3-p385.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for ubuntu.
Installing requirements for ubuntu.
Updating system........
Installing required packages: gawk, libgdbm-dev, libffi-dev....
Requirements installation successful.
Installing Ruby from source to: /usr/local/rvm/rubies/ruby-1.9.3-p385, this may take a while depending on your cpu(s)...
ruby-1.9.3-p385 - #downloading ruby-1.9.3-p385, this may take a while depending on your connection...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 9786k  100 9786k    0     0  2773k      0  0:00:03  0:00:03 --:--:-- 3017k
ruby-1.9.3-p385 - #extracting ruby-1.9.3-p385 to /usr/local/rvm/src/ruby-1.9.3-p385...
ruby-1.9.3-p385 - #applying patch /usr/local/rvm/patches/ruby/GH-488.patch.
ruby-1.9.3-p385 - #configuring.............................................
ruby-1.9.3-p385 - #post-configuration.
ruby-1.9.3-p385 - #compiling.....................................................................................................................-
ruby-1.9.3-p385 - #installing........................
ruby-1.9.3-p385 - #making binaries executable..
ruby-1.9.3-p385 - #downloading rubygems-2.2.2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  404k  100  404k    0     0   985k      0 --:--:-- --:--:-- --:--:-- 1735k
No checksum for downloaded archive, recording checksum in user configuration.
ruby-1.9.3-p385 - #extracting rubygems-2.2.2...
ruby-1.9.3-p385 - #removing old rubygems.........
ruby-1.9.3-p385 - #installing rubygems-2.2.2...............
ruby-1.9.3-p385 - #gemset created /usr/local/rvm/gems/ruby-1.9.3-p385@global
ruby-1.9.3-p385 - #importing gemset /usr/local/rvm/gemsets/global.gems.............................................................
ruby-1.9.3-p385 - #generating global wrappers.........
ruby-1.9.3-p385 - #gemset created /usr/local/rvm/gems/ruby-1.9.3-p385
ruby-1.9.3-p385 - #importing gemsetfile /usr/local/rvm/gemsets/default.gems evaluated to empty gem list
ruby-1.9.3-p385 - #generating default wrappers.........
ruby-1.9.3-p385 - #adjusting #shebangs for (gem irb erb ri rdoc testrb rake).
Install of ruby-1.9.3-p385 - #complete 
WARNING: Please be aware that you just installed a ruby that is no longer maintained (2014-02-23), for a list of maintained rubies visit:

    http://bugs.ruby-lang.org/projects/ruby/wiki/ReleaseEngineering

Please consider upgrading to ruby-2.1.1 which will have all of the latest security patches.
Ruby was built without documentation, to build it run: rvm docs generate-ri
root@precise32:~# 

```

**Comment by eedrummer** [comment] 2014-03-24 14:14
@marks I'm going to close this because it is a basically a duplicate of #117. I agree that this is an issue. I think we are close to a new release of popHealth. Currently, the master branch supports Ruby 2.0.0 and Ruby 2.1.1. So moving forward we will be on the latest and greatest version of Ruby.

**Closed as completed by eedrummer** 2014-03-24 14:14 UTC
